feat: added kubeconform tests
Ticket: MC-6864

Signed-off-by: Roberto Giovanardi <roberto.giovanardi@northern.tech>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -251,6 +251,42 @@ test:helm_chart_upgrade_from3.4:
     - helm history mender
     - make test
 
+test:kubeconform_tests:
+  tags:
+    - mender-qa-worker-generic-light
+  image: ${PIPELINE_TOOLBOX_IMAGE}
+  stage: test
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "master-next" || $RUN_HELM_CHART_INSTALL == "true" || $CI_COMMIT_TAG'
+  before_script:
+    - *set_eks_helmci_vars
+  script:
+    - |
+      echo "INFO - running kubeconform tests:"
+      while IFS= read -r version; do
+        full_version=${version}.0
+        echo "INFO - testing version ${full_version}"
+        helm template mender/ \
+          -f mender/values.yaml \
+          -f tests/keys.yaml \
+          -f tests/values-helmci.yaml \
+          --kube-version ${full_version} \
+        | kubeconform --kubernetes-version ${full_version}
+      done < <(eksctl version -o json | jq -r '.EKSServerSupportedVersions[]')
+    - | 
+      echo "DEBUG - run failed kubeconform tests: this should fail"
+      sed -i 's/apps\/v1/fakeapps\/v42/' mender/templates/gui-deploy.yaml
+      while IFS= read -r version; do
+        full_version=${version}.0
+        echo "INFO - testing version ${full_version}"
+        helm template mender/ \
+          -f mender/values.yaml \
+          -f tests/keys.yaml \
+          -f tests/values-helmci.yaml \
+          --kube-version ${full_version} \
+        | kubeconform --kubernetes-version ${full_version} \
+        || echo "INFO - test failed with version ${kubeversion}: this is expected"
+      done < <(eksctl version -o json | jq -r '.EKSServerSupportedVersions[]')
 
 publish:helm_chart_publishing:
   rules:
